module.exports = {
  AddReactions: "Thêm biểu tượng cảm xúc",
  Administrator: "Quản trị viên",
  AttachFiles: "Đính kèm tệp",
  BanMembers: "Cấm thành viên",
  ChangeNickname: "Đổi biệt danh",
  Connect: "Kết nối",
  CreateInstantInvite: "Tạo lời mời",
  CreatePrivateThreads: "Tạo kênh chủ đề riêng tư",
  CreatePublicThreads: "Tạo kênh chủ đề công khai",
  DeafenMembers: "Tắt tiếng thành viên",
  EmbedLinks: "Nhúng",
  KickMembers: "Đuổi thành viên",
  ManageChannels: "Quản lý kênh",
  ManageEmojisAndStickers: "Quản lý biểu tượng cảm xúc và sticker",
  ManageEvents: "Quản lý sự kiện",
  ManageGuild: "Quản lý máy chủ",
  ManageMessages: "Quản lý tin nhắn",
  ManageNicknames: "Quản lý biệt danh",
  ManageRoles: "Quản lý vai trò",
  ManageThreads: "Quản lý kênh chủ đề",
  ManageWebhooks: "Quản lý webhooks",
  MentionEveryone: "Đề cập mọi người",
  ModerateMembers: "Moderate Members",
  MoveMembers: "Di chuyển thành viên",
  MuteMembers: "Tắt âm thành viên",
  PrioritySpeaker: "Người nói ưu tiên",
  ReadMessageHistory: "Đọc lịch sử tin nhắn",
  RequestToSpeak: "Yêu cầu để nói",
  SendMessages: "Gửi tin nhắn",
  SendMessagesInThreads: "Gửi tin nhắn trong kênh chủ đề",
  SendTTSMessages: "Gửi tin nhắn Text-to-Speech",
  Speak: "Nói",
  Stream: "Video",
  UseApplicationCommands: "Sử dụng các lệnh ứng dụng",
  UseEmbeddedActivities: "Sử dụng các hoạt động",
  UseExternalEmojis: "Sử dụng biểu tượng cảm xúc bên ngoài",
  UseExternalStickers: "Sử dụng nhãn dán bên ngoài",
  UseVAD: "Sử dụng hoạt động kênh thoại",
  ViewAuditLog: "Xem nhật ký trỉnh sửa",
  ViewChannel: "Xem kênh",
  ViewGuildInsights: "Xem thông tin chi tiết về máy chủ",
};
